(()=>{const G="gh_games_v1",A="gh_ad_v1",S="gh_session_v1",D="gh_downloads_v1";const defaults=[
{id:"demo-1",title:"Neon Drift",description:"Скоростные заезды в неоновом городе с аркадной физикой.",cover:"https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=900&q=80",size:"842 MB",version:"1.4.2",platform:"Windows",url:"https://example.com/neon-drift.zip"},
{id:"demo-2",title:"Cyber Arena",description:"Тактические сражения на футуристических аренах.",cover:"https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=900&q=80",size:"1.1 GB",version:"2.0.1",platform:"Windows",url:"https://example.com/cyber-arena.zip"},
{id:"demo-3",title:"Pixel Quest",description:"Ретро-приключение с исследованием мира и секретами.",cover:"https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=900&q=80",size:"356 MB",version:"3.7.0",platform:"Android",url:"https://example.com/pixel-quest.apk"},
{id:"demo-4",title:"Moonfall",description:"Атмосферный космический экшен с исследованием планет.",cover:"https://images.unsplash.com/photo-1446776877081-d282a0f896e2?auto=format&fit=crop&w=900&q=80",size:"764 MB",version:"1.8.5",platform:"Windows",url:"https://example.com/moonfall.zip"},
{id:"demo-5",title:"Shadow Run",description:"Ночной экшен, где скорость и скрытность решают всё.",cover:"https://images.unsplash.com/photo-1511882150382-421056c89033?auto=format&fit=crop&w=900&q=80",size:"598 MB",version:"1.2.6",platform:"Android",url:"https://example.com/shadow-run.apk"},
{id:"demo-6",title:"Wild Lands",description:"Исследуй дикие земли, собирай ресурсы и строй базу.",cover:"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",size:"923 MB",version:"0.9.9",platform:"Windows",url:"https://example.com/wild-lands.zip"}];
const load=(k,f)=>{try{let v=JSON.parse(localStorage.getItem(k));return v??f}catch{return f}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));if(!localStorage.getItem(G))save(G,defaults);const games=()=>load(G,defaults),grid=document.getElementById("gamesGrid"),search=document.getElementById("searchInput"),filters=document.getElementById("categoryFilters"),empty=document.getElementById("emptyState"),session=load(S,null);
document.getElementById("year").textContent=new Date().getFullYear();const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const box=document.getElementById("headerActions");if(session?.username){box.innerHTML=`<span class="btn btn-ghost">👤 ${esc(session.username)}</span><button class="btn btn-primary" id="logoutBtn">Выйти</button>`;document.getElementById("logoutBtn").onclick=()=>{localStorage.removeItem(S);location.reload()}};
function renderFilters(){let cats=["Все",...new Set(games().map(g=>g.platform))];filters.innerHTML=cats.map((c,i)=>`<button class="filter-btn ${i?"":"active"}" data-cat="${esc(c)}">${esc(c)}</button>`).join("");filters.querySelectorAll(".filter-btn").forEach(b=>b.onclick=()=>{filters.querySelectorAll(".filter-btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");render()})}
function render(){let q=(search.value||"").toLowerCase().trim(),cat=filters.querySelector(".active")?.dataset.cat||"Все",list=games().filter(g=>(cat==="Все"||g.platform===cat)&&`${g.title} ${g.description} ${g.platform}`.toLowerCase().includes(q));grid.innerHTML=list.map(g=>`<article class="game-card"><div class="cover"><img src="${esc(g.cover)}" alt="${esc(g.title)}" loading="lazy" onerror="this.src='https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=900&q=80'"><span class="platform">${esc(g.platform)}</span></div><div class="game-body"><h3>${esc(g.title)}</h3><p>${esc(g.description)}</p><div class="game-meta"><span>${esc(g.size)}</span><span>v${esc(g.version)}</span></div><button class="btn btn-primary download-btn" data-id="${esc(g.id)}">СКАЧАТЬ <span>↓</span></button></div></article>`).join("");empty.classList.toggle("hidden",!!list.length);grid.querySelectorAll(".download-btn").forEach(b=>b.onclick=()=>openDownload(b.dataset.id))}
let timer=null,current=null;function openDownload(id){current=games().find(g=>g.id===id);if(!current)return;let m=document.getElementById("downloadModal"),c=document.getElementById("countdown"),r=document.getElementById("downloadReady"),t=document.getElementById("countdownText");document.getElementById("downloadGameName").textContent=current.title;r.classList.add("hidden");m.classList.remove("hidden");let n=10;c.textContent=n;t.textContent="Подождите немного — ссылка станет доступна автоматически.";clearInterval(timer);timer=setInterval(()=>{n--;c.textContent=n;if(n<=0){clearInterval(timer);c.textContent="✓";t.textContent="Загрузка подготовлена.";r.classList.remove("hidden")}},1000)}
document.getElementById("downloadClose").onclick=()=>{clearInterval(timer);document.getElementById("downloadModal").classList.add("hidden")};document.getElementById("downloadModal").onclick=e=>{if(e.target.id==="downloadModal"){clearInterval(timer);e.currentTarget.classList.add("hidden")}};document.getElementById("downloadReady").onclick=()=>{if(current){save(D,load(D,0)+1);location.href=current.url}};
search.oninput=render;document.getElementById("menuToggle").onclick=()=>{let n=document.querySelector(".main-nav");n.style.display=n.style.display==="flex"?"none":"flex";n.style.position="absolute";n.style.top="65px";n.style.left="0";n.style.right="0";n.style.padding="15px 20px";n.style.background="#0b0f18";n.style.flexDirection="column"};
function renderAd(){let h=localStorage.getItem(A)||"";["adTop","adBottom"].forEach(id=>document.getElementById(id).innerHTML=h?`<div class="ad-slot"><div class="ad-box">${h}</div></div>`:"")}renderFilters();render();renderAd()})()